language: node_js

node_js:
    - '8'

matrix:
    include:
    - os: windows
      dist: xenial
      sudo: required
    - os: osx

cache:
    yarn: true

notifications:
    email: false

install:
    - npm install electron-builder@next
    - npm install

deploy:
    provider: releases
    api_key: $ENCRYPTED_GITHUB_TOKEN
    skip_cleanup: true
    on:
        tags: true
